### ISSUE TITLE
Consider auto-resizing text boxes

### ISSUE THREAD

**Issue by kball** [benjie-git/CardStock#5]
I noticed watching my boys play with this that they both got confused/frustrated by typing into a text box and having the text not all be visible. 

I wonder if would be worth making the text labels auto-resize, either by autogrowing the box, or by automatically shrinking the font size to fit in the visible box (similar to keynote). We could still allow deliberate manipulation of the properties that override this auto scaling.

**Comment by benjie-git** [comment]
I think this is a great idea.  Offhand, I think my favorite option would be:
- While inline-editing a text label, its height can auto-grow, and then auto-shrink back to the original size, but not auto-shrink to smaller than it started.
- This autosizing would not apply when editing in the inspector, nor upon programmatic label.text changes.

What do you think of this plan?  Do you think we also need improvement in this area for text fields?

**Comment by benjie-git** [comment]
I tried out a few variations, and my new favorite option is just shrinking the font size to fit the label's size, instead of messing with the text box's size, which could potentially cause weird overlapping with other objects on the card. I've implemented this, and would love to hear whether this solves the problem for the kiddos.
